name: test_task_SoftCent
version: 1.0.0+1
publish_to: none
description: A Test project by HM Athir.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  dio: 4.0.6
  flutter_staggered_grid_view: ^0.4.0
  convex_bottom_bar: 3.0.0
  flutter: 
    sdk: flutter
  iconly: ^1.0.1

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

